In [48]:
import os
import sys
import torch
import torch.nn as nn
from torch.utils.data import Dataset, random_split
import PIL
import pandas as pd
from sklearn.model_selection import train_test_split
from torchvision.io import read_image
from itertools import chain
import pickle
from preprocess import ThaiOCRData

if torch.cuda.is_available():
    device = torch.device('cuda:3')
else:
    device = torch.device('cpu')

In [49]:
from preprocess import ThaiOCRData
from train import train

In [50]:
with open('train_dataset.pkl', 'rb') as f:
    loaded_train = pickle.load(f)

In [51]:
label_ = loaded_train[0][1]
label_str = loaded_train[0][0]

In [52]:
label_

'183'

In [47]:
loaded_train.class_to_idx

{'168': 0,
 '264': 1,
 '215': 2,
 '232': 3,
 '191': 4,
 '171': 5,
 '260': 6,
 '270': 7,
 '167': 8,
 '184': 9,
 '172': 10,
 '199': 11,
 '228': 12,
 '226': 13,
 '205': 14,
 '200': 15,
 '276': 16,
 '207': 17,
 '227': 18,
 '236': 19,
 '283': 20,
 '269': 21,
 '179': 22,
 '193': 23,
 '169': 24,
 '202': 25,
 '192': 26,
 '194': 27,
 '189': 28,
 '166': 29,
 '173': 30,
 '188': 31,
 '216': 32,
 '183': 33,
 '279': 34,
 '237': 35,
 '197': 36,
 '198': 37,
 '170': 38,
 '234': 39,
 '267': 40,
 '274': 41,
 '224': 42,
 '285': 43,
 '257': 44,
 '214': 45,
 '174': 46,
 '163': 47,
 '190': 48,
 '178': 49,
 '266': 50,
 '204': 51,
 '165': 52,
 '229': 53,
 '233': 54,
 '187': 55,
 '258': 56,
 '284': 57,
 '263': 58,
 '185': 59,
 '203': 60,
 '210': 61,
 '212': 62,
 '201': 63,
 '209': 64,
 '177': 65,
 '256': 66,
 '231': 67,
 '282': 68,
 '164': 69,
 '195': 70,
 '175': 71,
 '182': 72,
 '196': 73,
 '281': 74,
 '213': 75,
 '261': 76,
 '259': 77,
 '275': 78,
 '180': 79,
 '278': 80,
 '176': 81,
 '262': 82,
 '162': 83,
 '

In [39]:
label_

'183'

In [40]:
tensor_

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.]]], device='cuda:3')

In [41]:
for i in tensor_:
    print(i.size())

torch.Size([72, 48])


In [42]:
tensor_

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.]]], device='cuda:3')

In [43]:
len(loaded_train.indices)

250551

In [44]:
len(loaded_train)

250551

In [45]:
for item in loaded_train:
    print(item)

(tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.]]], device='cuda:3'), '183')
(tensor([[[1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:3'), '266')
(tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]], device='cuda:3'), '195')
(tensor([[[1.0000, 1.0000, 1.0000,  ..., 0.0000, 0.5938, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 0.0000, 0.5938, 1.0000],
     

KeyboardInterrupt: 

print("### labels.long().min()", labels.long().min())
print("### labels.min()", labels.min())

print("### labels1.long().min()", labels1.long().min())
print("### labels1.min()", labels1.min())

In [22]:
tensor_[0]

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.]], device='cuda:3')

for i in range(len(loaded_train)):
    #print(loaded_train[i][4])
    print(loaded_train[i][4].size())
    print(loaded_train[i][2])
    print()

In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda:1')
else:
    device = torch.device('cpu')

In [3]:
print(device)

cuda:1


In [53]:
from ML2 import generate_split, ThaiOCRData

Generating data splits for combined Thai + English...
If a single subset is sought, run with 'Thai', 'English', 'Special', or 'Numeric' as arg 1.
3


TypeError: object of type 'function' has no len()

In [54]:
training_dir = os.path.abspath("/scratch/lt2326-2926-h24/ThaiOCR/ThaiOCR-TrainigSet")

In [6]:
a = ("ddsdsad",)
len(a)

1

In [55]:
df, train, walking = generate_split(training_dir)


Generating data splits for combined Thai + English...
If a single subset is sought, run with 'Thai', 'English', 'Special', or 'Numeric' as arg 1.


In [4]:
subset_splits = []

In [ ]:
subset_splits.append([((),), ('engtestlabel', 'engtestpic'), ('engvallabel', 'engvalpic')])
subset_splits.append([('thaitrainlabel', 'thaitrainpic'), ('thaitestlabel', 'thaitestpic'), ('thaivallabel', 'thaivalpic')])

In [5]:
subset_splits.append([('engtrainlabel', 'engtrainpic'), ('engtestlabel', 'engtestpic'), ('engvallabel', 'engvalpic')])
subset_splits.append([('thaitrainlabel', 'thaitrainpic'), ('thaitestlabel', 'thaitestpic'), ('thaivallabel', 'thaivalpic')])

In [6]:


zipped = list(zip(*subset_splits))

#list(zip(subset_splits))

In [7]:
zipped

[(('engtrainlabel', 'engtrainpic'), ('thaitrainlabel', 'thaitrainpic')),
 (('engtestlabel', 'engtestpic'), ('thaitestlabel', 'thaitestpic')),
 (('engvallabel', 'engvalpic'), ('thaivallabel', 'thaivalpic'))]

In [40]:
zipped[0]

('etrain', 'ttrain')

In [41]:
len(zipped[0])

2

In [8]:


data_split = [tuple(chain(*split)) for split in zip(*subset_splits)]

#numbers = list(chain(odd, even))

In [9]:
data_split

[('engtrainlabel', 'engtrainpic', 'thaitrainlabel', 'thaitrainpic'),
 ('engtestlabel', 'engtestpic', 'thaitestlabel', 'thaitestpic'),
 ('engvallabel', 'engvalpic', 'thaivallabel', 'thaivalpic')]

In [ ]:
[train, test, valid list(zip(*subset_splits))]

In [22]:
list(zip(('etrain', 'etest', 'eval'), ('ttrain', 'ttest', 'teval')))

[('etrain', 'ttrain'), ('etest', 'ttest'), ('eval', 'teval')]

In [56]:
df

KKTS211_200_41_08_199.bmp PPTS211_200_41_10_199.bmp  \
label                          199                       199   
dpi                            200                       200   
typeface               bold_italic               bold_italic   

         Cdts213_200_41_22_199.bmp Cdts212_200_41_18_199.bmp  \
label                          199                       199   
dpi                            200                       200   
typeface               bold_italic               bold_italic   

         Cdtb213_200_40_20_199.bmp Ects211_200_41_08_199.bmp  \
label                          199                       199   
dpi                            200                       200   
typeface               bold_italic               bold_italic   

         FSTB213_200_40_22_199.bmp KKTB212_200_40_22_199.bmp  \
label                          199                       199   
dpi                            200                       200   
typeface               bold_italic               bold_italic   

         IRTB213_200_40_22_199.bmp PPTB212_200_40_16_199.bmp  ...  \
label                          199                       199  ...   
dpi                            200                       200  ...   
typeface               bold_italic               bold_italic  ...   

         BWEB311_300_10_08_075.bmp DLES322_300_11_16_075.bmp  \
label                          075                       075   
dpi                            300                       300   
typeface                    normal                    normal   

         JMEB311_300_10_08_075.bmp JMEB321_300_10_10_075.bmp  \
label                          075                       075   
dpi                            300                       300   
typeface                    normal                    normal   

         KKES312_300_11_18_075.bmp CDES322_300_11_16_075.bmp  \
label                          075                       075   
dpi                            300                       300   
typeface                    normal                    normal   

         ASEB321_300_10_10_075.bmp ASES323_300_11_22_075.bmp  \
label                          075                       075   
dpi                            300                       300   
typeface                    normal                    normal   

         DLEB311_300_10_14_075.bmp BWEB321_300_10_10_075.bmp  
label                          075                       075  
dpi                            300                       300  
typeface                    normal                    normal  

[3 rows x 489157 columns]

In [57]:
train

KKTS211_200_41_08_199.bmp PPTS211_200_41_10_199.bmp  \
typeface               bold_italic               bold_italic   
dpi                            200                       200   

         Cdts213_200_41_22_199.bmp Cdts212_200_41_18_199.bmp  \
typeface               bold_italic               bold_italic   
dpi                            200                       200   

         Cdtb213_200_40_20_199.bmp Ects211_200_41_08_199.bmp  \
typeface               bold_italic               bold_italic   
dpi                            200                       200   

         FSTB213_200_40_22_199.bmp KKTB212_200_40_22_199.bmp  \
typeface               bold_italic               bold_italic   
dpi                            200                       200   

         IRTB213_200_40_22_199.bmp PPTB212_200_40_16_199.bmp  ...  \
typeface               bold_italic               bold_italic  ...   
dpi                            200                       200  ...   

         BWEB311_300_10_08_075.bmp DLES322_300_11_16_075.bmp  \
typeface                    normal                    normal   
dpi                            300                       300   

         JMEB311_300_10_08_075.bmp JMEB321_300_10_10_075.bmp  \
typeface                    normal                    normal   
dpi                            300                       300   

         KKES312_300_11_18_075.bmp CDES322_300_11_16_075.bmp  \
typeface                    normal                    normal   
dpi                            300                       300   

         ASEB321_300_10_10_075.bmp ASES323_300_11_22_075.bmp  \
typeface                    normal                    normal   
dpi                            300                       300   

         DLEB311_300_10_14_075.bmp BWEB321_300_10_10_075.bmp  
typeface                    normal                    normal  
dpi                            300                       300  

[2 rows x 489157 columns]

In [58]:
thai = ThaiOCRData('thai')

In [59]:
len(thai)

AttributeError: 'ThaiOCRData' object has no attribute 'data_dict'

In [16]:
dir(thai)

['__add__',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']